export interface Robot {
  id: string;
  name: string;
  brand: string;
  sku: string;
  type: "Humanoid" | "Quadruped" | "Reception" | "Industrial";
  dof: number;
  torque: number;
  accentColor: string;
  rentalPrice: number;
  buyPrice: number;
  speed: number;       // 0-100
  strength: number;    // 0-100
  aiLevel: number;     // 0-100
  skillsInstalled: number;
  available: boolean;
  description: string;
  imageGradient: string;
}

export interface Skill {
  id: string;
  name: string;
  icon: string;
  author: string;
  authorType: "Verified company" | "Community" | "Official Dexio";
  version: string;
  description: string;
  category: "Navigation" | "Vision" | "Language" | "Industrial" | "Custom";
  compatibility: string[];
  price: number;       // 0 = free
  rating: number;      // 0-5
  installs: number;
  installed?: boolean;
  premium?: boolean;
}

export const ROBOT_IMAGES: Record<string, string> = {
  "agibot-x2-ultra": "/robot-x2-ultra.jpeg",
  "unitree-h1": "/robot-h1-pro.jpeg",
  "booster-t3": "/robot-t3-companion.jpeg",
  "delta-rx-500": "/robot-rx500.jpeg",
  "unitree-go2": "/robot-go2-pro.jpeg",
  "magic-lab-pm01": "/robot-pm01.jpeg",
};

export const robots: Robot[] = [
  {
    id: "agibot-x2-ultra",
    name: "X2 Ultra",
    brand: "Agibot",
    sku: "AGB-X2U-2025",
    type: "Humanoid",
    dof: 42,
    torque: 320,
    accentColor: "#0ea5e9",
    rentalPrice: 899,
    buyPrice: 189000,
    speed: 82,
    strength: 91,
    aiLevel: 88,
    skillsInstalled: 4,
    available: true,
    description: "Flagship humanoid with 42 DOF and advanced manipulation. Ideal for warehouse and logistics operations.",
    imageGradient: "radial-gradient(circle at 30% 40%, rgba(14,165,233,0.15), transparent 60%)",
  },
  {
    id: "unitree-h1",
    name: "H1 Pro",
    brand: "Unitree",
    sku: "UTR-H1P-2025",
    type: "Humanoid",
    dof: 38,
    torque: 280,
    accentColor: "#ef4444",
    rentalPrice: 749,
    buyPrice: 145000,
    speed: 94,
    strength: 76,
    aiLevel: 82,
    skillsInstalled: 3,
    available: true,
    description: "The fastest humanoid on the market. Built for speed-critical applications and dynamic environments.",
    imageGradient: "radial-gradient(circle at 70% 30%, rgba(239,68,68,0.15), transparent 60%)",
  },
  {
    id: "delta-rx-500",
    name: "RX-500",
    brand: "Delta Robots",
    sku: "DLT-RX5-2025",
    type: "Industrial",
    dof: 28,
    torque: 450,
    accentColor: "#10b981",
    rentalPrice: 599,
    buyPrice: 98000,
    speed: 65,
    strength: 98,
    aiLevel: 71,
    skillsInstalled: 6,
    available: false,
    description: "Industrial-grade strength with precision control. Designed for manufacturing and heavy assembly tasks.",
    imageGradient: "radial-gradient(circle at 50% 60%, rgba(16,185,129,0.15), transparent 60%)",
  },
  {
    id: "booster-t3",
    name: "T3 Companion",
    brand: "Booster",
    sku: "BST-T3C-2025",
    type: "Reception",
    dof: 24,
    torque: 120,
    accentColor: "#8b5cf6",
    rentalPrice: 299,
    buyPrice: 45000,
    speed: 55,
    strength: 35,
    aiLevel: 95,
    skillsInstalled: 8,
    available: true,
    description: "AI-first reception robot with natural language mastery. Perfect for hospitality and customer service.",
    imageGradient: "radial-gradient(circle at 40% 50%, rgba(139,92,246,0.15), transparent 60%)",
  },
  {
    id: "unitree-go2",
    name: "Go2 Pro",
    brand: "Unitree",
    sku: "UTR-G2P-2025",
    type: "Quadruped",
    dof: 12,
    torque: 180,
    accentColor: "#f59e0b",
    rentalPrice: 449,
    buyPrice: 68000,
    speed: 88,
    strength: 62,
    aiLevel: 78,
    skillsInstalled: 5,
    available: true,
    description: "Agile quadruped for terrain inspection, security patrols, and autonomous mapping in complex environments.",
    imageGradient: "radial-gradient(circle at 60% 40%, rgba(245,158,11,0.15), transparent 60%)",
  },
  {
    id: "magic-lab-pm01",
    name: "PM-01",
    brand: "Magic Lab",
    sku: "MGL-PM1-2025",
    type: "Humanoid",
    dof: 36,
    torque: 260,
    accentColor: "#06b6d4",
    rentalPrice: 679,
    buyPrice: 125000,
    speed: 72,
    strength: 84,
    aiLevel: 86,
    skillsInstalled: 4,
    available: true,
    description: "Balanced humanoid with exceptional dexterity. Excels at fine motor tasks and collaborative work.",
    imageGradient: "radial-gradient(circle at 35% 55%, rgba(6,182,212,0.15), transparent 60%)",
  },
];

export const skills: Skill[] = [
  {
    id: "nav-slam",
    name: "SLAM Navigation",
    icon: "M",
    author: "Dexio Labs",
    authorType: "Official Dexio",
    version: "3.2",
    description: "Real-time simultaneous localization and mapping for autonomous indoor navigation.",
    category: "Navigation",
    compatibility: ["Universal"],
    price: 49,
    rating: 4.8,
    installs: 3420,
  },
  {
    id: "vis-object-detect",
    name: "Object Detection Pro",
    icon: "O",
    author: "VisionAI",
    authorType: "Verified company",
    version: "2.1",
    description: "Multi-class object detection with 98.2% accuracy. Supports 1200+ object categories.",
    category: "Vision",
    compatibility: ["Universal"],
    price: 79,
    rating: 4.9,
    installs: 5100,
  },
  {
    id: "lang-natural-pl",
    name: "Natural Language PL",
    icon: "L",
    author: "LinguaTech",
    authorType: "Verified company",
    version: "4.0",
    description: "Full Polish language understanding with context-aware dialogue management.",
    category: "Language",
    compatibility: ["Universal"],
    price: 29,
    rating: 4.5,
    installs: 1890,
  },
  {
    id: "ind-welding",
    name: "Precision Welding",
    icon: "W",
    author: "IndustrialAI",
    authorType: "Verified company",
    version: "1.8",
    description: "Automated MIG/TIG welding with real-time seam tracking and quality inspection.",
    category: "Industrial",
    compatibility: ["Delta Robots", "Agibot"],
    price: 149,
    rating: 4.7,
    installs: 890,
  },
  {
    id: "nav-outdoor",
    name: "Outdoor Terrain",
    icon: "T",
    author: "PathFinder",
    authorType: "Community",
    version: "2.3",
    description: "GPS-aided outdoor navigation with terrain classification and obstacle avoidance.",
    category: "Navigation",
    compatibility: ["Unitree", "Agibot"],
    price: 39,
    rating: 4.3,
    installs: 2100,
  },
  {
    id: "vis-face-recog",
    name: "Face Recognition",
    icon: "F",
    author: "Dexio Labs",
    authorType: "Official Dexio",
    version: "3.0",
    description: "Privacy-compliant face detection and recognition with liveness checks.",
    category: "Vision",
    compatibility: ["Universal"],
    price: 59,
    rating: 4.6,
    installs: 4200,
  },
  {
    id: "lang-en-pro",
    name: "English Pro",
    icon: "E",
    author: "Dexio Labs",
    authorType: "Official Dexio",
    version: "5.1",
    description: "Advanced English NLU with sentiment analysis, intent recognition, and multi-turn dialogue.",
    category: "Language",
    compatibility: ["Universal"],
    price: 0,
    rating: 4.8,
    installs: 8900,
  },
  {
    id: "custom-brand-host",
    name: "Brand Host",
    icon: "B",
    author: "Dexio Labs",
    authorType: "Official Dexio",
    version: "2.0",
    description: "White-label hosting personality. Custom greetings, brand voice, and event scripting.",
    category: "Custom",
    compatibility: ["Universal"],
    price: 49,
    rating: 4.4,
    installs: 3100,
  },
  {
    id: "ind-pick-place",
    name: "Pick & Place",
    icon: "P",
    author: "RoboLogic",
    authorType: "Verified company",
    version: "3.1",
    description: "High-speed pick and place with adaptive grip force and conveyor synchronization.",
    category: "Industrial",
    compatibility: ["Agibot", "Delta Robots", "Magic Lab"],
    price: 89,
    rating: 4.7,
    installs: 2800,
  },
  {
    id: "vis-quality",
    name: "Quality Inspector",
    icon: "Q",
    author: "IndustrialAI",
    authorType: "Verified company",
    version: "1.5",
    description: "Visual quality inspection with defect classification. Sub-millimeter accuracy.",
    category: "Vision",
    compatibility: ["Delta Robots", "Agibot"],
    price: 119,
    rating: 4.5,
    installs: 1200,
    premium: true,
  },
  {
    id: "nav-elevator",
    name: "Elevator Control",
    icon: "V",
    author: "BuildingAI",
    authorType: "Community",
    version: "1.2",
    description: "Autonomous elevator interaction — call, enter, select floor, and exit safely.",
    category: "Navigation",
    compatibility: ["Universal"],
    price: 19,
    rating: 4.1,
    installs: 980,
  },
  {
    id: "custom-dance",
    name: "Dance Routines",
    icon: "D",
    author: "MotionCraft",
    authorType: "Community",
    version: "1.0",
    description: "Pre-choreographed dance routines for events and exhibitions. 12 styles included.",
    category: "Custom",
    compatibility: ["Unitree", "Agibot", "Booster"],
    price: 0,
    rating: 4.0,
    installs: 6500,
  },
];
