// Built-in knowledge base of popular humanoid and quadruped robots
// Sources: manufacturer specs, public datasheets

export interface RobotSpec {
  name: string;
  brand: string;
  type: "Humanoid" | "Quadruped" | "Reception" | "Industrial";
  dof: number;
  torque: number;
  weight: number;
  speed: number;       // 0-100 rating
  strength: number;    // 0-100 rating
  aiLevel: number;     // 0-100 rating
  batteryLife: number; // hours
  warranty: number;    // months
  description: string;
  suggestedRentalPrice: number; // EUR/day
  suggestedBuyPrice: number;    // EUR
  sku: string;
}

const ROBOTS: RobotSpec[] = [
  // ─── Unitree ───
  {
    name: "G1",
    brand: "Unitree",
    type: "Humanoid",
    dof: 43,
    torque: 120,
    weight: 35,
    speed: 70,
    strength: 45,
    aiLevel: 85,
    batteryLife: 2,
    warranty: 12,
    description: "Compact humanoid robot with 43 DOF and advanced dexterous manipulation. Features real-time whole-body control, 360° LiDAR perception, and GPU-accelerated AI inference. Ideal for research, light industrial tasks, and service applications. Walks at up to 2 m/s with dynamic balancing.",
    suggestedRentalPrice: 599,
    suggestedBuyPrice: 89000,
    sku: "UTR-G1-2025",
  },
  {
    name: "H1",
    brand: "Unitree",
    type: "Humanoid",
    dof: 26,
    torque: 360,
    weight: 47,
    speed: 90,
    strength: 75,
    aiLevel: 80,
    batteryLife: 4,
    warranty: 12,
    description: "Full-size humanoid built for speed and agility. Holds the record for fastest humanoid walking at 3.3 m/s. Features high-torque joint motors, 3D LiDAR, depth cameras, and IMU-based balance control. Designed for logistics, industrial inspection, and dynamic environments.",
    suggestedRentalPrice: 749,
    suggestedBuyPrice: 145000,
    sku: "UTR-H1-2025",
  },
  {
    name: "H1 Pro",
    brand: "Unitree",
    type: "Humanoid",
    dof: 38,
    torque: 380,
    weight: 50,
    speed: 94,
    strength: 78,
    aiLevel: 85,
    batteryLife: 4,
    warranty: 12,
    description: "Enhanced version of H1 with additional DOF for dexterous hands, upgraded AI compute, and improved battery. The fastest full-size humanoid available commercially. Built for warehouse automation, logistics, and advanced research.",
    suggestedRentalPrice: 849,
    suggestedBuyPrice: 168000,
    sku: "UTR-H1P-2025",
  },
  {
    name: "Go2",
    brand: "Unitree",
    type: "Quadruped",
    dof: 12,
    torque: 45,
    weight: 15,
    speed: 75,
    strength: 35,
    aiLevel: 72,
    batteryLife: 2,
    warranty: 12,
    description: "Agile quadruped robot with 4D LiDAR, intelligent companion features, and autonomous navigation. Can traverse stairs, rough terrain, and tight spaces. Ideal for security patrols, terrain mapping, and inspection tasks.",
    suggestedRentalPrice: 299,
    suggestedBuyPrice: 45000,
    sku: "UTR-G2-2025",
  },
  {
    name: "Go2 Pro",
    brand: "Unitree",
    type: "Quadruped",
    dof: 12,
    torque: 60,
    weight: 15,
    speed: 82,
    strength: 42,
    aiLevel: 78,
    batteryLife: 2.5,
    warranty: 12,
    description: "Professional-grade quadruped with enhanced compute, 4D LiDAR L2, and developer SDK. Supports ROS2 and custom AI model deployment. Built for autonomous inspection, security, and research applications.",
    suggestedRentalPrice: 449,
    suggestedBuyPrice: 68000,
    sku: "UTR-G2P-2025",
  },
  {
    name: "B2",
    brand: "Unitree",
    type: "Quadruped",
    dof: 12,
    torque: 280,
    weight: 60,
    speed: 80,
    strength: 85,
    aiLevel: 75,
    batteryLife: 4,
    warranty: 12,
    description: "Heavy-duty industrial quadruped capable of carrying 40kg payload. Features IP67 protection, all-terrain locomotion, and modular payload mounting. Designed for industrial inspection, construction site monitoring, and hazardous environment operations.",
    suggestedRentalPrice: 699,
    suggestedBuyPrice: 120000,
    sku: "UTR-B2-2025",
  },
  // ─── Tesla ───
  {
    name: "Optimus",
    brand: "Tesla",
    type: "Humanoid",
    dof: 28,
    torque: 180,
    weight: 57,
    speed: 55,
    strength: 60,
    aiLevel: 90,
    batteryLife: 8,
    warranty: 24,
    description: "Tesla's general-purpose humanoid robot powered by the same AI that drives Tesla vehicles. Features end-to-end neural network control, 11 DOF hands with adaptive grip, and Tesla's Dojo-trained vision system. Designed for repetitive manufacturing tasks and household assistance.",
    suggestedRentalPrice: 499,
    suggestedBuyPrice: 75000,
    sku: "TSL-OPT-2025",
  },
  {
    name: "Optimus Gen 2",
    brand: "Tesla",
    type: "Humanoid",
    dof: 32,
    torque: 200,
    weight: 52,
    speed: 65,
    strength: 65,
    aiLevel: 92,
    batteryLife: 10,
    warranty: 24,
    description: "Second generation Tesla Bot with 30% faster walking speed, improved 11-DOF hands with tactile sensing, and enhanced neural network inference. Lighter frame with Tesla-designed actuators. Purpose-built for factory automation and general assistance.",
    suggestedRentalPrice: 599,
    suggestedBuyPrice: 85000,
    sku: "TSL-OPT2-2025",
  },
  // ─── Boston Dynamics ───
  {
    name: "Atlas",
    brand: "Boston Dynamics",
    type: "Humanoid",
    dof: 28,
    torque: 400,
    weight: 89,
    speed: 85,
    strength: 95,
    aiLevel: 88,
    batteryLife: 1.5,
    warranty: 12,
    description: "The most dynamic humanoid robot ever built. Electric Atlas features unprecedented agility — backflips, parkour, and dynamic manipulation. Designed for automotive manufacturing and industrial applications requiring superhuman dexterity and strength.",
    suggestedRentalPrice: 1499,
    suggestedBuyPrice: 350000,
    sku: "BD-ATLS-2025",
  },
  {
    name: "Spot",
    brand: "Boston Dynamics",
    type: "Quadruped",
    dof: 12,
    torque: 120,
    weight: 32,
    speed: 78,
    strength: 55,
    aiLevel: 82,
    batteryLife: 1.5,
    warranty: 12,
    description: "Industry-proven quadruped for autonomous inspection and data collection. Features 360° perception, autonomous navigation, and modular payload system. Deployed in power plants, construction sites, and oil & gas facilities worldwide.",
    suggestedRentalPrice: 899,
    suggestedBuyPrice: 175000,
    sku: "BD-SPOT-2025",
  },
  {
    name: "Stretch",
    brand: "Boston Dynamics",
    type: "Industrial",
    dof: 8,
    torque: 500,
    weight: 1200,
    speed: 45,
    strength: 98,
    aiLevel: 70,
    batteryLife: 8,
    warranty: 12,
    description: "Mobile robot designed for warehouse automation. Features a vacuum gripper array capable of moving up to 800 cases per hour. Autonomous navigation in warehouse environments with computer vision-based box detection.",
    suggestedRentalPrice: 1299,
    suggestedBuyPrice: 280000,
    sku: "BD-STRCH-2025",
  },
  // ─── Figure ───
  {
    name: "Figure 02",
    brand: "Figure",
    type: "Humanoid",
    dof: 40,
    torque: 250,
    weight: 60,
    speed: 65,
    strength: 70,
    aiLevel: 92,
    batteryLife: 5,
    warranty: 12,
    description: "Next-generation humanoid with OpenAI-powered conversational AI and advanced manipulation. 16 DOF hands enable human-like dexterity. Designed for commercial deployment in manufacturing, logistics, and retail environments.",
    suggestedRentalPrice: 899,
    suggestedBuyPrice: 195000,
    sku: "FIG-02-2025",
  },
  {
    name: "Figure 01",
    brand: "Figure",
    type: "Humanoid",
    dof: 32,
    torque: 200,
    weight: 60,
    speed: 55,
    strength: 65,
    aiLevel: 88,
    batteryLife: 5,
    warranty: 12,
    description: "First-generation general-purpose humanoid from Figure AI. Features end-to-end learned locomotion, vision-language model integration, and dexterous bi-manual manipulation. Targeted at logistics and light manufacturing.",
    suggestedRentalPrice: 749,
    suggestedBuyPrice: 165000,
    sku: "FIG-01-2025",
  },
  // ─── 1X Technologies ───
  {
    name: "NEO",
    brand: "1X Technologies",
    type: "Humanoid",
    dof: 30,
    torque: 100,
    weight: 30,
    speed: 60,
    strength: 40,
    aiLevel: 82,
    batteryLife: 4,
    warranty: 12,
    description: "Lightweight bipedal humanoid designed for safe human coexistence. Features compliant actuators, embodied AI trained in simulation, and natural movement. Focused on home assistance, elderly care, and service applications.",
    suggestedRentalPrice: 449,
    suggestedBuyPrice: 65000,
    sku: "1X-NEO-2025",
  },
  {
    name: "EVE",
    brand: "1X Technologies",
    type: "Humanoid",
    dof: 24,
    torque: 80,
    weight: 86,
    speed: 50,
    strength: 55,
    aiLevel: 78,
    batteryLife: 6,
    warranty: 12,
    description: "Wheeled humanoid robot with upper body dexterity and mobile base. Designed for security patrol, facility management, and logistics. Features autonomous navigation, manipulation, and conversational AI capabilities.",
    suggestedRentalPrice: 399,
    suggestedBuyPrice: 55000,
    sku: "1X-EVE-2025",
  },
  // ─── Agility Robotics ───
  {
    name: "Digit",
    brand: "Agility Robotics",
    type: "Humanoid",
    dof: 20,
    torque: 150,
    weight: 45,
    speed: 60,
    strength: 55,
    aiLevel: 75,
    batteryLife: 4,
    warranty: 12,
    description: "Purpose-built for logistics, Digit can carry up to 16kg totes and navigate human spaces autonomously. Features dynamic balancing, perception-based manipulation, and fleet management integration. Deployed in Amazon warehouses.",
    suggestedRentalPrice: 699,
    suggestedBuyPrice: 130000,
    sku: "AGR-DGT-2025",
  },
  // ─── Agibot ───
  {
    name: "X2 Ultra",
    brand: "Agibot",
    type: "Humanoid",
    dof: 42,
    torque: 320,
    weight: 65,
    speed: 82,
    strength: 91,
    aiLevel: 88,
    batteryLife: 3,
    warranty: 24,
    description: "Flagship humanoid with 42 DOF and advanced manipulation capabilities. Features high-torque actuators, multi-modal perception, and GPU-accelerated AI. Ideal for warehouse automation, logistics, and complex industrial operations.",
    suggestedRentalPrice: 899,
    suggestedBuyPrice: 189000,
    sku: "AGB-X2U-2025",
  },
  // ─── Booster ───
  {
    name: "T3 Companion",
    brand: "Booster",
    type: "Reception",
    dof: 24,
    torque: 120,
    weight: 28,
    speed: 55,
    strength: 35,
    aiLevel: 95,
    batteryLife: 6,
    warranty: 24,
    description: "AI-first reception robot with natural language mastery. Features a display face for emotional expression, premium speakers, and multi-language support. Perfect for hospitality, retail, and customer service applications.",
    suggestedRentalPrice: 299,
    suggestedBuyPrice: 45000,
    sku: "BST-T3C-2025",
  },
  // ─── Softbank ───
  {
    name: "Pepper",
    brand: "SoftBank Robotics",
    type: "Reception",
    dof: 20,
    torque: 40,
    weight: 28,
    speed: 35,
    strength: 20,
    aiLevel: 70,
    batteryLife: 12,
    warranty: 12,
    description: "The world's most recognized social robot. Features emotion recognition, multi-language dialogue, and a 10-inch touch display. Deployed in over 2,000 locations worldwide for customer engagement, retail assistance, and education.",
    suggestedRentalPrice: 199,
    suggestedBuyPrice: 28000,
    sku: "SBR-PPR-2025",
  },
  {
    name: "NAO",
    brand: "SoftBank Robotics",
    type: "Reception",
    dof: 25,
    torque: 15,
    weight: 5,
    speed: 30,
    strength: 10,
    aiLevel: 68,
    batteryLife: 1.5,
    warranty: 12,
    description: "Compact 58cm humanoid used in education, research, and assisted therapy. Features voice recognition, face detection, and programmable behavior engine. Over 13,000 units deployed in schools and research labs worldwide.",
    suggestedRentalPrice: 99,
    suggestedBuyPrice: 12000,
    sku: "SBR-NAO-2025",
  },
  // ─── UBTECH ───
  {
    name: "Walker X",
    brand: "UBTECH",
    type: "Humanoid",
    dof: 41,
    torque: 200,
    weight: 63,
    speed: 50,
    strength: 60,
    aiLevel: 78,
    batteryLife: 3,
    warranty: 12,
    description: "Full-size humanoid with 41 DOF including dexterous 7-DOF hands. Features SLAM navigation, visual servoing, and compliant whole-body control. Targeted at smart manufacturing, commercial services, and smart home applications.",
    suggestedRentalPrice: 599,
    suggestedBuyPrice: 110000,
    sku: "UBT-WLX-2025",
  },
  // ─── Fourier Intelligence ───
  {
    name: "GR-2",
    brand: "Fourier Intelligence",
    type: "Humanoid",
    dof: 53,
    torque: 350,
    weight: 63,
    speed: 60,
    strength: 80,
    aiLevel: 80,
    batteryLife: 2,
    warranty: 12,
    description: "Highest-DOF commercial humanoid with 53 degrees of freedom including 12-DOF dexterous hands. Features FSA (Fourier Smart Actuator) joints with force feedback. Designed for rehabilitation, research, and industrial applications.",
    suggestedRentalPrice: 799,
    suggestedBuyPrice: 155000,
    sku: "FI-GR2-2025",
  },
  // ─── Xiaomi ───
  {
    name: "CyberOne",
    brand: "Xiaomi",
    type: "Humanoid",
    dof: 21,
    torque: 150,
    weight: 52,
    speed: 45,
    strength: 50,
    aiLevel: 72,
    batteryLife: 2,
    warranty: 12,
    description: "Xiaomi's full-size humanoid featuring MiSense emotion recognition, 3D environment reconstruction, and natural language interaction. Slim humanoid design at 177cm height. Focused on smart home and personal assistant applications.",
    suggestedRentalPrice: 399,
    suggestedBuyPrice: 65000,
    sku: "XMI-CYB1-2025",
  },
  // ─── Delta Robots ───
  {
    name: "RX-500",
    brand: "Delta Robots",
    type: "Industrial",
    dof: 28,
    torque: 450,
    weight: 120,
    speed: 65,
    strength: 98,
    aiLevel: 71,
    batteryLife: 8,
    warranty: 24,
    description: "Industrial-grade robot with extreme strength and precision control. Features high-torque servo motors, industrial-grade sensors, and real-time force feedback. Designed for heavy manufacturing, assembly, and welding operations.",
    suggestedRentalPrice: 599,
    suggestedBuyPrice: 98000,
    sku: "DLT-RX5-2025",
  },
  // ─── Magic Lab ───
  {
    name: "PM-01",
    brand: "Magic Lab",
    type: "Humanoid",
    dof: 36,
    torque: 260,
    weight: 45,
    speed: 72,
    strength: 84,
    aiLevel: 86,
    batteryLife: 3,
    warranty: 12,
    description: "Balanced humanoid with exceptional dexterity. Features precision 6-DOF hands, multi-modal perception, and reinforcement learning-based locomotion. Excels at fine motor tasks, collaborative work, and adaptive manufacturing.",
    suggestedRentalPrice: 679,
    suggestedBuyPrice: 125000,
    sku: "MGL-PM1-2025",
  },
  // ─── Apptronik ───
  {
    name: "Apollo",
    brand: "Apptronik",
    type: "Humanoid",
    dof: 28,
    torque: 220,
    weight: 73,
    speed: 55,
    strength: 70,
    aiLevel: 80,
    batteryLife: 4,
    warranty: 12,
    description: "General-purpose humanoid designed for real-world commercial deployment. Features modular actuators, swappable battery packs, and safe human collaboration. Partnered with Mercedes-Benz and NASA for industrial and space applications.",
    suggestedRentalPrice: 799,
    suggestedBuyPrice: 160000,
    sku: "APT-APL-2025",
  },
  // ─── Sanctuary AI ───
  {
    name: "Phoenix",
    brand: "Sanctuary AI",
    type: "Humanoid",
    dof: 34,
    torque: 180,
    weight: 70,
    speed: 50,
    strength: 60,
    aiLevel: 94,
    batteryLife: 4,
    warranty: 12,
    description: "AI-first humanoid powered by Carbon — the world's first human-like AI control system. Features 20-DOF hands with near-human dexterity. Focused on general-purpose work including retail, manufacturing, and logistics.",
    suggestedRentalPrice: 849,
    suggestedBuyPrice: 180000,
    sku: "SAN-PHX-2025",
  },
];

/**
 * Search the knowledge base for a robot matching the query.
 * Matches against name, brand, or "brand name" combination.
 */
export function findRobotSpec(query: string): RobotSpec | null {
  const q = query.toLowerCase().trim();
  if (!q) return null;

  // Exact match on "brand name" or "name"
  for (const r of ROBOTS) {
    const fullName = `${r.brand} ${r.name}`.toLowerCase();
    if (fullName === q || r.name.toLowerCase() === q) return r;
  }

  // Partial match
  for (const r of ROBOTS) {
    const fullName = `${r.brand} ${r.name}`.toLowerCase();
    if (fullName.includes(q) || q.includes(r.name.toLowerCase())) return r;
  }

  // Word-based match
  const words = q.split(/\s+/);
  for (const r of ROBOTS) {
    const haystack = `${r.brand} ${r.name}`.toLowerCase();
    if (words.every((w) => haystack.includes(w))) return r;
  }

  return null;
}

/**
 * Get all known robot names for autocomplete suggestions.
 */
export function getAllRobotNames(): string[] {
  return ROBOTS.map((r) => `${r.brand} ${r.name}`);
}
